debugging deployment stage

diff --git a/.github/workflows/marketup-frontend.yaml b/.github/workflows/marketup-frontend.yaml
--- a/.github/workflows/marketup-frontend.yaml
+++ b/.github/workflows/marketup-frontend.yaml
@@ -57,7 +57,11 @@ jobs:
         working-directory: terraform/
         run: |
           RAW_OUTPUT=$(terraform output -raw ec2_public_ip)
-          CLEANED_IP=$(echo "$RAW_OUTPUT" | sed -e 's/[^0-9.]//g')
+          CLEANED_IP=$(echo "$RAW_OUTPUT" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
+          if [[ -z "$CLEANED_IP" ]]; then
+            echo "Failed to extract a valid public IP address." >&2
+            exit 1
+          fi
           echo "EC2_PUBLIC_IP=$CLEANED_IP" >> $GITHUB_ENV
 
       # Step 6: Verify EC2 Public IP
